title: Curso general de R
description: Notas del Curso de R, para el curso Introducción a la Estadística y Probabilidad CM-274
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
